### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by MeatCow** [MeatCow/paws-patrol-lhl#8]
As a user, I would like to be able to use this web app on my desktop.

## Todo

- [x] Create mockups
- [x] Create home page
- [x] Create nav bar
- [x] Create account page
- [x] #29
- [x] Create Perimeter Page
- [x] Create Add device management page
- [x] #21
- [x] Create contact us page
- [x] #28
